### ISSUE TITLE
uninstall script

### ISSUE THREAD

**Issue by ottonet** [magento-hackathon/FireGento_FlexCms#3]
The extension adds to two tables to the database and adds two attributes to eav_attribute; display_attribute and flexcms_cms_page. After uninstallation of the extension Magento will generate an error once you try to open Catalog/Manage Categories, as it is looking for the source_model belonging to "display_attribute", which it can't find as this source_model does not exist anymore. 

An uninstall script would ensure one can do a clean un-install without any database issues or errors.

**Comment by avstudnitz** [comment]
We may also include the necessary SQL queries in the Readme.

**Comment by avstudnitz** [comment]
Added to Readme. Untestet yet.
